import type { MetadataRoute } from "next";

import { brand, installedApp } from "@/lib/content";

/**
 * The web app manifest — what a phone reads when someone adds Paris Bites to
 * their home screen.
 *
 * Next's file convention, so it is served at /manifest.webmanifest and the
 * <link rel="manifest"> tag is emitted automatically.
 *
 * Every URL here is relative. The manifest resolves them against its own
 * location, which means the same build installs correctly from a Vercel
 * preview, the production domain, or localhost — and none of it depends on
 * NEXT_PUBLIC_SITE_URL being set.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${brand.name} — ${brand.descriptor}`,
    short_name: installedApp.shortName,
    description: brand.description,
    lang: "en-IN",
    dir: "ltr",
    start_url: "/",
    scope: "/",
    /* standalone, not fullscreen: the customer keeps the status bar with its
       clock and battery, which is what they expect of an app they opened to
       order dessert — fullscreen is for games. */
    display: "standalone",
    orientation: "portrait",
    background_color: installedApp.background,
    theme_color: installedApp.theme,
    categories: ["food", "shopping", "lifestyle"],
    icons: [
      /* `any` is the icon as drawn; `maskable` is the same cup shrunk into
         the safe zone on a filled ground, because Android crops launcher
         icons to a circle or squircle and would otherwise shave the edges
         off this one. Both are generated by scripts/prep-icons.mjs. */
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icons/maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
